name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 1. Exit immediately if any command fails
            set -e

            # 2. Navigate to project folder
            cd /root/iut-community

            # 3. Force-update the repository
            # This wipes any local changes on the server that might prevent a 'git pull'
            git fetch origin main
            git reset --hard origin/main

            # 4. Re-create the .env file
            cat > server/.env << EOF
                  AIRFLOW_UID=1000
                  FERNET_KEY=${{ secrets.FERNET_KEY }}
                  AIRFLOW_PROJ_DIR=./timetable_web_scraping
                  _AIRFLOW_WWW_USER_USERNAME=admin
                  _AIRFLOW_WWW_USER_PASSWORD=${{ secrets.AIRFLOW_PASSWORD }}
                  DB_HOST=backend-postgres
                  DB_PORT=5432
                  DB_NAME=${{ secrets.DB_NAME }}
                  DB_USER=${{ secrets.DB_USER }}
                  DB_PASSWORD=${{ secrets.DB_PASSWORD }}
                  EOF

                  cd server
                  sudo docker compose up -d --build --remove-orphans
                  sudo docker image prune -f

            # 5. Build and Restart Services
            cd server
            
            # Pull new base images (like Airflow/Postgres) if they've been updated
            sudo docker compose pull
            
            # Rebuild your custom images and restart the containers
            # The --build flag ensures your latest code changes are baked into the image
            sudo docker compose up -d --build

            # 6. Housekeeping: Remove old, dangling images to save disk space
            sudo docker image prune -f